-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Anamakine: 127.0.0.1
-- Üretim Zamanı: 24 Tem 2025, 16:57:47
-- Sunucu sürümü: 10.4.32-MariaDB
-- PHP Sürümü: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Veritabanı: `otorezerv`
--

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `vehicles`
--

CREATE TABLE `vehicles` (
                            `id` int(11) NOT NULL,
                            `company_id` int(11) DEFAULT NULL,
                            `title` varchar(100) DEFAULT NULL,
                            `brand` varchar(50) DEFAULT NULL,
                            `model` varchar(50) DEFAULT NULL,
                            `year` int(11) DEFAULT NULL,
                            `price` decimal(10,2) DEFAULT NULL,
                            `price_currency` varchar(10) DEFAULT NULL,
                            `is_for_rent` tinyint(1) DEFAULT 0,
                            `is_for_sale` tinyint(1) DEFAULT 0,
                            `status` enum('available','reserved','sold','rented') DEFAULT 'available',
                            `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
                            `plate` varchar(20) DEFAULT NULL,
                            `is_plate_hidden` tinyint(1) DEFAULT 0,
                            `km` int(11) DEFAULT NULL,
                            `is_km_hidden` tinyint(1) DEFAULT 0,
                            `location_address` varchar(255) DEFAULT NULL,
                            `location_country_id` int(11) DEFAULT NULL,
                            `location_city_id` int(11) DEFAULT NULL,
                            `location_district_id` int(11) DEFAULT NULL,
                            `gear_type` enum('manual','automatic','semi-automatic') DEFAULT 'automatic',
                            `fuel_type` enum('petrol','diesel','lpg','electric','hybrid') DEFAULT 'petrol',
                            `engine_size` decimal(5,2) DEFAULT NULL COMMENT 'Motor hacmi litre cinsinden',
                            `horse_power` int(11) DEFAULT NULL COMMENT 'Motor gücü',
                            `color` varchar(30) DEFAULT NULL,
                            `body_type` enum('sedan','hatchback','suv','pickup','coupe','convertible','van','other') DEFAULT NULL,
                            `description` text DEFAULT NULL,
                            `rental_type` enum('daily','weekly','monthly','none') DEFAULT 'none',
                            `min_rent_duration` int(11) DEFAULT NULL COMMENT 'Minimum kiralama süresi gün cinsinden',
                            `min_rent_duration_unit` varchar(10) DEFAULT NULL,
                            `max_rent_duration` int(11) DEFAULT NULL COMMENT 'Maksimum kiralama süresi gün cinsinden',
                            `max_rent_duration_unit` varchar(10) DEFAULT NULL,
                            `tramers_price` decimal(10,2) DEFAULT NULL COMMENT 'Araç tramers fiyatı',
                            `tramers_price_currency` varchar(10) DEFAULT NULL,
                            `traction` enum('fwd','rwd','awd','4wd','other') DEFAULT NULL COMMENT 'Çekiş tipi',
                            `rental_km_limit` int(11) DEFAULT NULL COMMENT 'Kiralık araçlar için km sınırı',
                            `over_km_price` decimal(10,2) DEFAULT NULL COMMENT 'Kiralama km sınırı aşıldığında km başı ücret',
                            `over_km_price_currency` varchar(10) DEFAULT NULL,
                            `heavy_damage_record` tinyint(4) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Tablo döküm verisi `vehicles`
--

INSERT INTO `vehicles` (`id`, `company_id`, `title`, `brand`, `model`, `year`, `price`, `price_currency`, `is_for_rent`, `is_for_sale`, `status`, `created_at`, `plate`, `is_plate_hidden`, `km`, `is_km_hidden`, `location_address`, `location_country_id`, `location_city_id`, `location_district_id`, `gear_type`, `fuel_type`, `engine_size`, `horse_power`, `color`, `body_type`, `description`, `rental_type`, `min_rent_duration`, `min_rent_duration_unit`, `max_rent_duration`, `max_rent_duration_unit`, `tramers_price`, `tramers_price_currency`, `traction`, `rental_km_limit`, `over_km_price`, `over_km_price_currency`, `heavy_damage_record`) VALUES
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   (1, 1, '2020 Renault Clio Kiralık', 'Renault', 'Clio', 2020, 850.00, 'TRY', 1, 0, 'available', '2025-07-20 07:00:00', '', 0, 0, 0, 'Bağdat Caddesi No:100', 1, 76, 939, 'automatic', 'petrol', 1.20, 132, '#FFFFFF', 'sedan', '<p>asdasda</p>\r\n', 'none', 0, 'gun', 0, 'gun', 0.00, 'TRY', '', 0, 0.00, 'TRY', 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   (2, 1, '2022 Fiat Egea Satılık', 'Fiat', 'Egea', 2022, 385000.00, NULL, 0, 1, 'available', '2025-07-20 08:00:00', NULL, 0, NULL, 0, 'Atatürk Bulvarı No:25', 1, 6, 601, 'automatic', 'petrol', 1.60, 265, '#000000', 'sedan', 'asfacsa', 'none', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   (3, 2, '2019 BMW 320i Kiralık', 'BMW', '320i', 2019, 1200.00, 'TRY', 1, 0, 'available', '2025-07-20 09:00:00', '', 0, 0, 0, 'Adnann', 1, 9, 125, 'automatic', 'petrol', 1.60, 120, '#FF0000', 'sedan', '<p>zxczxczx</p>\r\n', 'none', 0, 'gun', 0, 'gun', 0.00, 'TRY', '', 0, 0.00, 'TRY', 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   (4, 2, '2018 Toyota Corolla Satılık', 'Toyota', 'Corolla', 2018, 310000.00, 'TRY', 0, 1, 'sold', '2025-07-20 10:00:00', '', 0, 0, 0, 'Alsancak Mahallesi 1469. Sokak', 1, 35, 462, 'automatic', 'petrol', 3.00, 150, '#808080', 'sedan', '<p>e213e1w21</p>\r\n', 'none', 0, 'gun', 0, 'gun', 0.00, 'TRY', '', 0, 0.00, 'TRY', 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   (10, 1, '2023 Toyota Corolla Kiralık', 'Toyota', 'Corolla', 2023, 450.00, 'TRY', 1, 0, 'available', '2025-07-21 15:01:48', '34ABC123', 0, 15000, 0, 'İstanbul, Kadıköy Mah.', 1, 34, 434, 'automatic', 'petrol', 1.60, 132, '#8B0000', 'sedan', '<p>Bakımları tam, g&uuml;nl&uuml;k kiralık.</p>\r\n', 'daily', 1, 'gun', 30, 'gun', 150000.00, 'TRY', 'fwd', 100, 0.50, 'TRY', 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   (11, 1, '2021 BMW X5 Satılık', 'BMW', 'X5', 2021, 950000.00, NULL, 0, 1, 'available', '2025-07-21 15:01:48', '06XYZ789', 0, 60000, 0, 'Ankara, Çankaya İlçesi', 1, 6, 62, 'automatic', 'diesel', 3.02, 265, '#0000FF', 'suv', '<p>İkinci el, full donanım.111</p>\r\n', 'none', 0, NULL, 0, NULL, 2200000.00, NULL, 'awd', 0, 0.00, NULL, 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   (12, 1, '2022 Renault Clio Kiralık', 'Renault', 'Clio', 2022, 320.00, NULL, 1, 0, 'rented', '2025-07-21 15:01:48', '35DEF456', 1, 22000, 1, 'İzmir, Konak', 1, 35, 301, 'manual', 'lpg', 1.20, 120, '#FFD700', 'hatchback', 'Yakıt cimrisi, şehir içi ideal.', 'weekly', 7, NULL, 90, NULL, 65000.00, NULL, 'fwd', 200, 0.30, NULL, 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   (13, 3, '2020 Ford Transit Satılık', 'Ford', 'Transit', 2020, 450000.00, NULL, 0, 1, 'sold', '2025-07-21 15:01:48', '34GHI789', 0, 100000, 0, 'İstanbul, Esenler', 1, 34, 34, 'manual', 'diesel', 2.20, 150, '#FFFFFF', 'van', 'İş amaçlı uygun.', 'none', NULL, NULL, NULL, NULL, 80000.00, NULL, 'rwd', NULL, NULL, NULL, 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   (14, 2, '2024 Tesla Model 3 Kiralık', 'Tesla', 'Model 3', 2024, 1000.00, NULL, 1, 0, 'available', '2025-07-21 15:01:48', '34TES123', 0, 5000, 0, 'İstanbul, Beşiktaş', 1, 34, 23, 'automatic', 'electric', NULL, 283, '#000000', 'sedan', 'Sıfır km elektrikli araç.', 'monthly', 30, NULL, 365, NULL, 300000.00, NULL, 'rwd', 300, 1.00, NULL, 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   (15, 1, 'Sıfırdan farksız', 'TOGG', 'T10X', 2024, 2100000.00, NULL, 0, 1, 'available', '2025-07-21 21:15:22', '34ASD123', 1, 15487, 0, 'mugeee', 1, 3, 27, 'automatic', 'electric', 1.60, 500, '#FF1493', 'suv', '<p>fasfcasfafa harika</p>\r\n', 'none', 1, NULL, 2, NULL, 1.00, NULL, 'rwd', 100, 100.00, NULL, 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   (16, 1, 'Deneme aracı', 'Opel', 'Corsa', 2022, 1070000.00, 'EUR', 1, 1, 'available', '2025-07-22 22:07:20', '77AS123', 0, 15000, 0, 'Açık aAdres', 1, 25, 314, 'automatic', 'petrol', 1.20, 105, '#8B0000', 'hatchback', '<p>&Ouml;ğretmenden temiz ara&ccedil;</p>\r\n', 'none', 1, 'gun', 2, 'ay', 2672.00, 'TRY', 'fwd', 0, 50.00, 'USD', 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   (18, 1, 'Cillop gibi kasa', 'BMW', 'F10', 2017, 1765000.00, 'TRY', 1, 1, 'available', '2025-07-23 14:21:32', '81ASD112', 0, 210547, 0, 'Düzce Merkez Patlıyo herkez', 1, 81, 972, 'automatic', 'petrol', 1.60, 180, '#000000', 'sedan', '<p>Harika bişey ya lore&ouml; ipsum falan filan</p>\r\n', 'daily', 10, 'gun', 3, 'ay', 1000.00, 'USD', 'rwd', 20000, 10.00, 'EUR', 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   (29, 1, 'Uygun fiyatlı aile aracı', 'Toyota', 'Corolla', 2020, 310000.00, 'TRY', 0, 1, 'available', '2025-07-23 17:06:34', '34ABC123', 0, 48000, 0, 'Kadıköy, İstanbul', 1, 34, 436, 'automatic', 'petrol', 1.60, 132, '#FFFFFF', 'sedan', '<p>Bakımlı, sorunsuz ara&ccedil;. 1. elden.</p>\r\n', 'none', 0, 'gun', 0, 'gun', 12000.00, 'TRY', 'fwd', 0, 0.00, 'TRY', 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   (30, 2, 'Elektrikli şehir içi araç', 'Renault', 'ZOE', 2022, 720000.00, 'TRY', 1, 0, 'available', '2025-07-23 17:06:34', '06EV456', 1, 12000, 0, 'Çankaya, Ankara', 1, 6, 45, 'automatic', 'electric', 0.00, 110, '#0000FF', 'hatchback', 'Elektrikli araç, düşük maliyet.', 'daily', 1, 'day', 7, 'day', NULL, NULL, 'fwd', 200, 3.50, 'TRY', 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   (31, 1, 'SUV 4x4 maceraperestler için', 'Jeep', 'Wrangler', 2019, 1550000.00, 'TRY', 0, 1, 'available', '2025-07-23 17:06:34', '35JEEP78', 0, 89000, 0, 'Bornova, İzmir', 1, 35, 463, 'manual', 'diesel', 2.80, 200, '#2f4f4f', 'suv', '<p>Zorlu arazi koşullarına uygun, y&uuml;ksek performans.</p>\r\n', 'none', 0, 'gun', 0, 'gun', 30000.00, 'TRY', '4wd', 0, 0.00, 'TRY', 1),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   (32, 2, 'Konforlu kiralık araç', 'BMW', '520i', 2021, 4500.00, 'TRY', 1, 0, 'available', '2025-07-23 17:06:34', '34BMW520', 1, 25000, 1, 'Beşiktaş, İstanbul', 1, 34, 3, 'automatic', 'petrol', 2.00, 184, '#808080', 'sedan', 'Haftalık ve aylık kiralamaya uygun.', 'weekly', 1, 'week', 4, 'week', NULL, NULL, 'rwd', 1000, 5.00, 'TRY', 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   (33, 2, 'Pickup iş aracı', 'Ford', 'Ranger', 2018, 795000.00, 'TRY', 0, 1, 'reserved', '2025-07-23 17:06:34', '16FORDR4', 0, 112000, 0, 'Nilüfer, Bursa', 1, 16, 7, 'automatic', 'diesel', 3.20, 200, '#FF0000', 'pickup', 'İş amaçlı kullanılmış, sağlam.', 'none', NULL, NULL, NULL, NULL, 15000.00, 'TRY', '4wd', NULL, NULL, NULL, 1),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   (34, 1, 'Ekonomik günlük kiralık', 'Fiat', 'Egea', 2022, 1000.00, 'TRY', 1, 0, 'available', '2025-07-23 17:06:34', '34EGEA22', 1, 18000, 0, 'Bakırköy, İstanbul', 1, 34, 426, 'manual', 'petrol', 1.40, 95, '#FFFFFF', 'sedan', '<p>G&uuml;nl&uuml;k kiralık olarak idealdir.</p>\r\n', 'daily', 1, 'gun', 14, 'gun', 0.00, 'TRY', 'fwd', 150, 2.00, 'TRY', 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   (35, 1, 'Lüks spor araç', 'Porsche', '911 Carrera', 2020, 4750000.00, 'TRY', 0, 1, 'available', '2025-07-23 17:06:34', '34POR911', 0, 21000, 0, 'Sarıyer, İstanbul', 1, 34, 435, 'automatic', 'petrol', 3.00, 450, '#ffa500', 'coupe', '<p>L&uuml;ks ve performans isteyenler i&ccedil;in.</p>\r\n', 'none', 0, 'gun', 0, 'gun', 50000.00, 'TRY', 'rwd', 0, 0.00, 'TRY', 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   (36, 1, 'Geniş aile aracı', 'Volkswagen', 'Transporter', 2017, 985000.00, 'TRY', 0, 1, 'sold', '2025-07-23 17:06:34', '06VWTRP7', 1, 145000, 1, 'Yenimahalle, Ankara', 1, 6, 60, 'manual', 'diesel', 2.00, 150, '#808080', 'van', '<p>Aile ve iş i&ccedil;in ideal geniş ara&ccedil;.</p>\r\n', 'none', 0, 'gun', 0, 'gun', 18000.00, 'TRY', 'fwd', 0, 0.00, 'TRY', 1),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   (37, 2, 'Kompakt hibrit şehir aracı', 'Toyota', 'Yaris Hybrid', 2023, 975000.00, 'TRY', 1, 1, 'available', '2025-07-23 17:06:34', '34HYR2023', 0, 7000, 0, 'Ataşehir, İstanbul', 1, 34, 424, 'automatic', 'hybrid', 1.50, 116, '#000000', 'hatchback', '<p>Hem satış hem kiralama opsiyonlu.</p>\r\n', 'monthly', 1, 'ay', 3, 'yil', 1000.00, 'USD', 'fwd', 2500, 4.50, 'EUR', 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   (38, 2, 'Cabrio yazlık keyfi', 'Mazda', 'MX-5', 2016, 1290000.00, 'TRY', 0, 1, 'available', '2025-07-23 17:06:34', '35MX5CABR', 0, 54000, 0, 'Konak, İzmir', 1, 35, 475, 'manual', 'petrol', 2.00, 160, '#8B0000', 'convertible', '<p>Yaz aylarında keyifli s&uuml;r&uuml;şler.</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>HAHAHAHHA</strong></p>\r\n', 'none', 0, 'gun', 0, 'gun', 25000.00, 'TRY', 'rwd', 0, 0.00, 'TRY', 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   (39, 1, '2021 Audi A3 Sportback', 'Audi', 'A3', 2021, 820000.00, 'TRY', 0, 1, 'available', '2025-07-24 13:01:15', '34AUD001', 0, 42000, 0, 'Istanbul, Turkey', 1, 34, 1, 'automatic', 'petrol', 1.40, 150, '#1E1E1E', 'hatchback', 'Bakımlı, şehir içi kullanılmış, kazasız araç.', 'none', NULL, NULL, NULL, NULL, 0.00, NULL, 'fwd', NULL, NULL, NULL, 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   (40, 2, '2022 Honda HR-V e:HEV', 'Honda', 'HR-V', 2022, 950000.00, 'TRY', 1, 1, 'available', '2025-07-24 13:01:15', '06HND987', 0, 18000, 0, 'Ankara, Turkey', 1, 6, 3, 'automatic', 'hybrid', 1.50, 131, '#FFFFFF', 'suv', 'Yüksek donanım, elektrik destekli hibrit sistem.', 'weekly', 3, 'day', 15, 'day', 0.00, NULL, 'fwd', 600, 2.50, 'TRY', 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   (41, 1, '2023 Skoda Superb Style', 'Skoda', 'Superb', 2023, 1150000.00, 'TRY', 0, 1, 'reserved', '2025-07-24 13:01:15', '34SKD888', 0, 12000, 0, 'Istanbul, Turkey', 1, 34, 4, 'automatic', 'diesel', 2.00, 190, '#2C3E50', 'sedan', 'Yeni kasa, full paket, fabrika garantili.', 'none', NULL, NULL, NULL, NULL, 0.00, NULL, 'fwd', NULL, NULL, NULL, 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   (42, 2, '2020 Hyundai i20 Elite', 'Hyundai', 'i20', 2020, 570000.00, 'TRY', 1, 0, 'available', '2025-07-24 13:01:15', '06HYD123', 0, 58000, 0, 'Ankara, Turkey', 1, 6, 7, 'manual', 'petrol', 1.20, 84, '#2980B9', 'hatchback', 'Uygun fiyatlı kiralık araç. Sorunsuz çalışır.', 'daily', 1, 'day', 30, 'day', 0.00, NULL, 'fwd', 300, 1.50, 'TRY', 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   (43, 1, '2023 Volvo XC40 Recharge', 'Volvo', 'XC40', 2023, 1480000.00, 'TRY', 0, 1, 'available', '2025-07-24 13:01:15', '34VLV404', 0, 9000, 0, 'Istanbul, Turkey', 1, 34, 5, 'automatic', 'electric', NULL, 231, '#34495E', 'suv', 'Tam elektrikli Volvo SUV. Full donanım.', 'none', NULL, NULL, NULL, NULL, 0.00, NULL, 'awd', NULL, NULL, NULL, 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   (44, 2, '2018 Nissan Qashqai Tekna', 'Nissan', 'Qashqai', 2018, 620000.00, 'TRY', 0, 1, 'sold', '2025-07-24 13:01:15', '06NSN321', 1, 95000, 1, 'Ankara, Turkey', 1, 6, 2, 'automatic', 'diesel', 1.50, 110, '#8E44AD', 'suv', 'Aile aracı, düzenli servisli, tramer kaydı yok.', 'none', NULL, NULL, NULL, NULL, 2100.00, 'TRY', 'fwd', NULL, NULL, NULL, 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   (45, 1, '2023 Cupra Born Electric', 'Cupra', 'Born', 2023, 1420000.00, 'TRY', 1, 0, 'available', '2025-07-24 13:01:15', '34CPR222', 0, 6000, 0, 'Istanbul, Turkey', 1, 34, 1, 'automatic', 'electric', NULL, 204, '#F39C12', 'hatchback', 'Sportif elektrikli araç, yüksek menzil.', 'monthly', 1, 'month', 6, 'month', 0.00, NULL, 'rwd', 1800, 3.20, 'TRY', 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   (46, 2, '2019 Kia Sportage Concept Plus', 'Kia', 'Sportage', 2019, 730000.00, 'TRY', 0, 1, 'available', '2025-07-24 13:01:15', '06KIA999', 0, 67000, 0, 'Ankara, Turkey', 1, 6, 6, 'automatic', 'petrol', 1.60, 177, '#E74C3C', 'suv', 'Crossover SUV, ferah ve rahat kullanım.', 'none', NULL, NULL, NULL, NULL, 1500.00, 'TRY', 'awd', NULL, NULL, NULL, 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   (47, 1, '2022 Seat Leon FR', 'Seat', 'Leon', 2022, 810000.00, 'TRY', 0, 1, 'available', '2025-07-24 13:01:15', '34STL555', 0, 21000, 0, 'Istanbul, Turkey', 1, 34, 426, 'automatic', 'petrol', 1.50, 150, '#d35400', 'hatchback', '<p>FR donanım paketi, dinamik s&uuml;r&uuml;ş.</p>\r\n', 'none', 0, 'gun', 0, 'gun', 0.00, 'TRY', 'fwd', 0, 0.00, 'TRY', 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   (48, 2, '2020 Mitsubishi L200 4x4', 'Mitsubishi', 'L200', 2020, 890000.00, 'TRY', 1, 1, 'available', '2025-07-24 13:01:15', '06MTS444', 0, 49000, 0, 'Ankara, Turkey', 1, 6, 4, 'manual', 'diesel', 2.40, 181, '#27AE60', 'pickup', 'Arazi koşullarına uygun güçlü 4x4 pickup.', 'weekly', 2, 'week', 6, 'week', 0.00, NULL, '4wd', 800, 4.50, 'TRY', 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   (56, 1, 'asdasdfa', 'dasdfa', 'fasfa', 2017, 0.00, 'TRY', 0, 0, 'available', '2025-07-24 14:22:09', '03AA999', 0, 50000, 1, '', 1, 4, 47, 'automatic', 'petrol', 0.00, 0, '#FFFFFF', 'sedan', '', 'none', 0, 'gun', 0, 'gun', 0.00, 'TRY', '', 0, 0.00, 'TRY', 0);

--
-- Dökümü yapılmış tablolar için indeksler
--

--
-- Tablo için indeksler `vehicles`
--
ALTER TABLE `vehicles`
    ADD PRIMARY KEY (`id`),
  ADD KEY `company_id` (`company_id`);

--
-- Dökümü yapılmış tablolar için AUTO_INCREMENT değeri
--

--
-- Tablo için AUTO_INCREMENT değeri `vehicles`
--
ALTER TABLE `vehicles`
    MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=57;

--
-- Dökümü yapılmış tablolar için kısıtlamalar
--

--
-- Tablo kısıtlamaları `vehicles`
--
ALTER TABLE `vehicles`
    ADD CONSTRAINT `vehicles_ibfk_1` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
